### ISSUE TITLE
Missing in Registry

### ISSUE THREAD

**Issue by maticzav** [sindresorhus/ink-link#2]
First, Sindre thanks for this great package! 💙 

Did you by any chance forgot to publish it to the `npm`? 
It seems like I cannot find it there, but would love to use it for my next project! 😄

**Comment by sindresorhus** [comment]
Oh, weird. That's a first. I was sure I did it. Maybe the publish process failed for some reason and I didn't notice. Thanks for letting me know. Fixed :)

**Comment by maticzav** [comment]
Thanks!
