### ISSUE TITLE
Feature request: option to disable fallback

### ISSUE THREAD

**Issue by colinking** [sindresorhus/ink-link#4]
re:

> For unsupported terminals, the link will be printed in parens after the text: My website (https://sindresorhus.com).

What do you think of adding an optional boolean prop that indicates whether or not to perform this fallback? (`fallback: boolean`?) It should default to performing the fallback (the current behavior), so that it is backwards compatible.

I'm working on a CLI where I've sprinkled in some links, but I've found that links are sometimes just supplied purely for convenience. In that case, ideally the fallback would be disabled since it just takes up valuable space in the CLI output!

Would be happy to open a PR if so. I would just conditionally override the `fallback` parameter from [`terminal-link`](https://github.com/sindresorhus/terminal-link#fallback).

**Comment by sindresorhus** [comment]
Makes sense. PR welcome :)
